INSERT IGNORE INTO `{prefix}permissions` (`code`, `name`, `group_name`) VALUES
('system.settings',    '系統設定管理',     'system'),
('system.install',     '系統安裝設定',     'system'),
('user.manage',        '使用者管理',       'user'),
('user.view',          '查看使用者列表',   'user'),
('role.manage',        '角色權限管理',     'role'),
('board.manage',       '看板管理',         'board'),
('board.view_all',     '查看所有看板',     'board'),
('board.view_public',  '查看公開看板',     'board'),
('stage.manage',       '狀態欄位管理',     'stage'),
('card.create',        '建立卡片',         'card'),
('card.edit_all',      '編輯所有卡片',     'card'),
('card.edit_own',      '編輯自己的卡片',   'card'),
('card.delete',        '刪除卡片',         'card'),
('card.drag_all',      '拖拉所有卡片',     'card'),
('card.drag_own',      '拖拉自己的卡片',   'card'),
('card.approve',       '核准卡片',         'card'),
('card.assign',        '指派負責人',       'card'),
('card.view_public',   '查看公開卡片',     'card'),
('wish.submit',        '提交許願表單',     'wish'),
('wish.manage',        '管理許願提案',     'wish'),
('api_config.manage',  'API 設定管理',     'api'),
('audit_log.view',     '查看操作紀錄',     'audit');
