CREATE TABLE IF NOT EXISTS `{prefix}roles` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `slug` VARCHAR(50) NOT NULL UNIQUE,
    `name` VARCHAR(100) NOT NULL,
    `description` TEXT NULL,
    `level` TINYINT UNSIGNED NOT NULL DEFAULT 99,
    `is_system` TINYINT(1) NOT NULL DEFAULT 0,
    `permissions` TEXT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
