CREATE TABLE IF NOT EXISTS `{prefix}cards` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `board_id` INT UNSIGNED NOT NULL,
    `stage_id` INT UNSIGNED NOT NULL,
    `title` VARCHAR(500) NOT NULL,
    `description` TEXT NULL,
    `source` VARCHAR(50) NOT NULL DEFAULT 'manual',
    `source_wish_id` INT UNSIGNED NULL,
    `proposer_user_id` INT UNSIGNED NULL,
    `assignee_id` INT UNSIGNED NULL,
    `approved_by_user_id` INT UNSIGNED NULL,
    `priority` ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
    `is_public` TINYINT(1) NOT NULL DEFAULT 0,
    `sort_order` INT NOT NULL DEFAULT 0,
    `published_at` DATETIME NULL,
    `created_by` INT UNSIGNED NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_board_stage` (`board_id`, `stage_id`),
    INDEX `idx_assignee` (`assignee_id`),
    INDEX `idx_proposer` (`proposer_user_id`),
    INDEX `idx_public` (`is_public`),
    INDEX `idx_priority` (`priority`),
    FOREIGN KEY (`board_id`) REFERENCES `{prefix}boards`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`stage_id`) REFERENCES `{prefix}stages`(`id`) ON DELETE RESTRICT,
    FOREIGN KEY (`proposer_user_id`) REFERENCES `{prefix}users`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`assignee_id`) REFERENCES `{prefix}users`(`id`) ON DELETE SET NULL,
    FOREIGN KEY (`approved_by_user_id`) REFERENCES `{prefix}users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
